name: start-run
description: 'Start E2E tests on selected ENV'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Env (ex: dev-minor)*'     
        required: false
        default: ''
      runId:
        description: 'Run ID (ex: 9341)'     
        required: false
        default: ''
      portal:
        description: 'Portal (ex: acp OR ap OR cp OR lis OR lp OR pp OR tp)'
        required: false
        default: ''
      grep:
        description: 'Grep (ex: 6363 OR C6363 OR C6363|C6364|C6368 ...)'
        required: false
        default: ''
      test:
        description: 'Test filename (ex: user OR practiceGroup ...)'
        required: false
        default: ''
jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: start-run
        run: echo "hi"